### ISSUE TITLE
incompatibility issue with other plugins declaring the same types

### ISSUE THREAD

**Issue by adamjakab** [adamjakab/BeetsPluginGoingRunning#15]
When both acousticbrainz and goingrunning plugins are activated beets exits with the following error:

```bash
Traceback (most recent call last):
  File "/Users/jackisback/opt/miniconda3/envs/beetsdevel/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/Users/jackisback/opt/miniconda3/envs/beetsdevel/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/Users/jackisback/opt/miniconda3/envs/beetsdevel/lib/python3.7/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/Users/jackisback/opt/miniconda3/envs/beetsdevel/lib/python3.7/site-packages/beets/ui/__init__.py", line 1148, in _setup
    library.Item._types.update(plugins.types(library.Item))
  File "/Users/jackisback/opt/miniconda3/envs/beetsdevel/lib/python3.7/site-packages/beets/plugins.py", line 344, in types
    u'another type.'.format(plugin.name, field)
beets.plugins.PluginConflictException: Plugin acousticbrainz defines flexible field average_loudness which has already been defined with another type.
```
Removing one of either plugins, the problem goes away.

**Comment by adamjakab** [comment]
Opened issue for Beets: https://github.com/beetbox/beets/issues/3520

**Comment by adamjakab** [comment]
In general, the incompatibility with AB is the result of a bug in the core of beets in which there is an erroneous type comparison of Flexible Fields declared by different plugins.
